dubbo:
  application:
    name: login_name
  consumer:
    check: false
  protocol:
    port: -1
  registry:
    address: zookeeper://192.168.114.168:2181
    check: false
    timeout: 50000
    retries: 3
spring:
  datasource:
    url: jdbc:mysql:///user_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

